### ISSUE TITLE
after installing, update_all.sh takes ages

### ISSUE THREAD

**Issue by valerino** [funkycochise/Coin-Op#3]
as the title says, after installing your script, issuing update_all.sh as normal (with the mame-getter option set, with update alternatives et al.) really takes ages (around 5 minutes). before it was way faster.
any way to fix it ?

~~~
###############################################################################
#==============================================================================#
################################################################################

Downloading the most recent mame-merged-set-getter.sh script.
 


STARTING: MAME-GETTER

INI file has been modified.

Performing a full update.

Finding all .mra files in /media/fat/_Arcade and in recursive directores.

2664 .mra files found in total.

Skipping MAME files that already exist

Downloading ROMs to /media/fat/games/mame - Be Patient!!!


SUCCESS!

~~~

**Comment by funkycochise** [comment]
There was several mras added that mame getter had difficulties to get.
I fixed this several days ago. The related roms are downloaded by coinop itself.
So mame getter in update_all is not necessary.

**Comment by valerino** [comment]
> There was several mras added that mame getter had difficulties to get. I fixed this several days ago. The related roms are downloaded by coinop itself. So mame getter in update_all is not necessary.

ok, thanks! so, to perform regular mister updates, it is ok to first run install_coinop.sh, then update_all.sh (with mame getter disabled), right ?

**Comment by funkycochise** [comment]
No, run update_all.sh first
then install_coinop.sh
